---
title: "Medication"
output: html_document
---


```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(vroom)
library(lubridate)
```

```{r}
source('utils.R')
table_var <- function(df, var, n = 100, max_n = nrow(df)){
  df %>% 
    select(!!enquo(var)) %>% 
    slice(1:max_n) %>% 
    table() %>% 
    sort(decreasing = T) %>%
    head(n)
}
```

```{r}
system.time(
  meds <- vroom('../Penn_ICU_Data/ICU PTS COHORT MEDS.csv', delim = ',',
                n_max = 50000000)
)
# save(lab_values, file = '../Penn_ICU_Data/lab_values_small.Rdata')
# load('../Penn_ICU_Data/lab_values_small.Rdata')'
```

```{r}
head(meds)
# table_var(meds, ORDER_NAME)
treat_hyperkalimia <- meds %>%
  slice(grep('insulin|dextrose', ORDER_NAME, ignore.case = T))
head(treat_hyperkalimia)
table_var(treat_hyperkalimia, ORDER_NAME, n = 200) %>%
  as_tibble() %>%
  write_csv('../Penn_ICU_Data/dextrose_insulin.csv')
```


```{r}
small_treat <- treat_hyperkalimia[1:100,] 
small_treat <- treat_hyperkalimia[1:100,] %>%
  group_by(VISIT_NUM) %>%
  slice(grep('insulin', ORDER_NAME, ignore.case = T)) %>%
  
  arrange(ORDER_DATE) %>%
  summarise(min_dif = diff(ORDER_DATE))
```

