---
title: "Analyze vitals"
output: html_document
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(vroom)
library(lubridate)
```


## Utils

Load utility functions:

```{r}
source('utils.R')
table_var <- function(df, var, n = 100, max_n = nrow(df)){
  df %>% 
    select(!!enquo(var)) %>% 
    slice(1:max_n) %>% 
    table() %>% 
    sort(decreasing = T) %>%
    head(n)
}
```

### Vitals

```{r}
system.time(
  vitals <- vroom('../Penn_ICU_Data/ICU PTS COHORT VITALS.csv', delim = ',')
)

# remove all-NA columns
# summary(vitals$VITAL_NOTE)
# summary(vitals$VITAL_DEVICE)
vitals <- vitals %>%
  select(-c(VITAL_NOTE, VITAL_DEVICE))

head(vitals)

vitals_first_mil <- slice(vitals, 1:10^6)
# save(lab_values, file = '../Penn_ICU_Data/lab_values_small.Rdata')
# load('../Penn_ICU_Data/lab_values_small.Rdata')
table_var(vitals, VITAL_DESCRIPTION, max_n = 10^6)

```

### Procedures

```{r}
system.time(
  procedures <- vroom('../Penn_ICU_Data/ICU PTS COHORT PROCEDURES.csv', delim = ',')
)
head(procedures)
procedures %>%
  slice(grep('transfus', DESCRIPTION, ignore.case = T)) %>%
  table_var(DESCRIPTION) %>%
  as_tibble() %>%
  write_csv('../Penn_ICU_Data/transfus.csv')
procedures %>%
  table_var(DESCRIPTION)

procedures_with_prbc <- procedures %>%
  filter(DESCRIPTION == 'Packed cell transfusion') %>%
  select(-c(CPT_MODIFIER, CODE_STANDARD_MASTER_NAME)) %>%
  mutate(proc_time = mdy_hms(PROC_DATE),
         hours = hour(proc_time) + 
           minute(proc_time)/60 + 
           second(proc_time)/3600)
head(procedures_with_prbc)
procedures_with_prbc$PROC_DATE %>%
  mdy_hms() %>%
  hour() %>%
  table() %>%
  as_tibble() %>%
  write_csv('../Penn_ICU_Data/proc_hours.csv')

table(cut(procedures_with_prbc$hours, seq(0, 24, 1), include.lowest = T)) %>%
  as_tibble(validate = F) %>%
  write_csv('../Penn_ICU_Data/proc_hours_from_midnight.csv')

```


```{r}
procedures_not_midnight <- procedures_with_prbc %>%
  filter(hours > 0)

load('vitals_filtered_prbc.Rdata')

sum(duplicated(procedures_not_midnight[, 2]))

vitals_filtered <- vitals_filtered %>%
  mutate(enc_date = ymd_hms(performed_date) - 
           dseconds(performed_date_offset_seconds),
         post_rep_date = enc_date + 
           dseconds(post_repletion_val_date_offset_seconds),
         dosage = paste(performed_dose, performed_unit_of_measure),
         medication_name = gsub('potassium chloride 20 mEq in 100 mL inj.', 
                                'potassium chloride 20 mEq/100 mL IVPB -', 
                                medication_name),
         medication_name = gsub('potassium chloride 20 mEq in 100 mL inj.', 
                                'potassium chloride 20 mEq/100 mL IVPB -', 
                                medication_name),
         medication_name = gsub('potassium chloride 20 mEq/50 mL IVPB_ -',
                                'potassium chloride 20 mEq/50 mL IVPB -', 
                                medication_name))

vitals_filtered %>%
  group_by(medication_name) %>%
  count(dosage) %>%
  filter(n > 50) %>%
  write_csv('../Penn_ICU_Data/potassium_dosage.csv')

sum(duplicated(vitals_prbc$visit_num))

prbc_vitals <- tibble()
for (i in seq.int(nrow(procedures_not_midnight))){
  prbc_i <- procedures_not_midnight[i, ] %>%
    mutate(proc_time = mdy_hms(PROC_DATE),
           VISIT_NUM = as.character(VISIT_NUM)) %>%
    rename(visit_num = 'VISIT_NUM')
  
  prbc_vitals <- vitals_prbc %>%
    filter(visit_num == prbc_i$visit_num) %>%
    left_join(prbc_i, by = 'visit_num') %>%
    rbind(prbc_vitals, .)
}
prbc_vitals <- prbc_vitals %>%
  mutate(prbc_to_post_repletion_result_hr = 
           interval(proc_time, post_rep_date)/hours(1)) %>%
  filter((prbc_to_post_repletion_result_hr > 0) & (prbc_to_post_repletion_result_hr < 24))

sum(duplicated(prbc_vitals$visit_num))
# 7 duplicated visit_num's

lm(post_repletion_val ~ performed_dose + pre_repletion_val + is_cad + is_chf + is_ckd + 
     on_loop_diuretic + on_acetazolamide + on_thiazide + on_spironolactone + 
     on_tpn + is_rhabdo + is_dialysis + given_dialysis + age +
     prbc_to_post_repletion_result_hr, 
   data = prbc_vitals) %>%
  summary() %>%
  broom::tidy() %>%
  mutate(padj = p.adjust(p.value, method = 'BH'))

ggplot(prbc_vitals, aes(x = prbc_to_post_repletion_result_hr,
                        y = post_repletion_val)) + 
  geom_point() +
  labs(x = 'Hours after PRBC', y = 'Potassium value') + 
  geom_smooth(method = 'lm')

summary(prbc_vitals$prbc_to_post_repletion_result_hr)
prbc_vitals %>%
  select(proc_time, post_rep_date, prbc_to_post_repletion_result_hr)
```


Among 1018 non-midnight PRBC transfusions, only 60 has a corresponding Potassium level read after the transfusion (some are after a few days which we should ignore). Within 24 hours, there is little correlation between the number of hours after PRBC initiation (I assume this is what PROC_TIME indicates) and Potassium level.


```{r}
lm(post_repletion_val ~ performed_dose + pre_repletion_val + is_cad + is_chf + is_ckd + 
     on_loop_diuretic + on_acetazolamide + on_thiazide + on_spironolactone + 
     on_tpn + is_rhabdo + is_dialysis + given_dialysis + age +
     , 
   data = prbc_vitals) %>%
  summary() %>%
  broom::tidy() %>%
  mutate(padj = p.adjust(p.value, method = 'BH'))
```

